#!/bin/bash
#
# battery status script
#

BATTERY=/proc/acpi/battery/BAT0

  REM_CAP=`grep "^remaining capacity" $BATTERY/state | awk '{ print $3 }'`
  FULL_CAP=`grep "^last full capacity" $BATTERY/info | awk '{ print $4 }'`
  BATSTATE=`grep "^charging state" $BATTERY/state | awk '{ print $3 }'`
  CHARGE=`echo $(( $REM_CAP * 100 / $FULL_CAP ))`

  COLOUR="<fc=#FF0000>"

  case "${BATSTATE}" in
     'charged')
     BATSTT="=="
     ;;
     'charging')
     BATSTT="++"
     ;;
     'discharging')
     BATSTT="--"
     ;;
  esac

  if [ "$CHARGE" -gt "10" ]
  then
     COLOUR="<fc=#FFA500>"
  fi

  if [ "$CHARGE" -gt "60" ]
  then
     COLOUR="<fc=#00FF00>"
  fi

  echo -e "Batt: ${COLOUR}${CHARGE}% ${BATSTT}</fc>"
