#!/bin/bash
#
# battery status script
#

BATTERY=`acpi -b`
PERCENT=`echo $BATTERY | awk '{ print $4 }'`
COLOUR="<fc=#FF0000>"

 if [ "${PERCENT//[!0-9]}" -gt "10" ]
 then
    COLOUR="<fc=#FFA500>"
 fi

 if [ "${PERCENT//[!0-9]}" -gt "60" ]
 then
    COLOUR="<fc=#00FF00>"
 fi

 echo -e "batt: ${COLOUR}${PERCENT%%,}</fc>"
